name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  start-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Start Target App
        run: |
          cd app
          npm install
          node server.js &
          sleep 15

  zap_scan:
    needs: start-app
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zaproxy/zaproxy:stable
      options: --user root
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: OWASP ZAP Baseline Scan
        run: |
          zap-baseline.py -t http://localhost:3000 -g gen.conf -r zap_scan.md -J zap_scan.json
          
      - name: OWASP ZAP Full Scan
        if: github.event_name == 'workflow_dispatch'
        run: |
          zap-full-scan.py -t http://localhost:3000 -g gen.conf -r zap_scan.md -J zap_scan.json
          
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_scan.md
            zap_scan.json