name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Weekly scans
  workflow_dispatch:
    inputs:
      target_url:
        description: 'URL to scan'
        required: true
        default: 'http://localhost:3000'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    container:
      image: owasp/zap2docker-stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Target App
        run: |
          cd app
          npm install
          node server.js &
          sleep 15
          
      - name: Baseline Scan
        run: |
          zap-baseline.py -t ${{ inputs.target_url || 'http://localhost:3000' }} \
          -c .zap/rules.tsv \
          -r zap-report.html
          
      - name: Full Scan (on demand)
        if: github.event_name == 'workflow_dispatch'
        run: |
          zap-full-scan.py -t ${{ inputs.target_url }} \
          -P .zap/policies/API-scan.policy \
          -J zap-report.json
          
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap-report.html
            zap-report.json
          retention-days: 7