name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      app:
        image: node:18
        ports:
          - 3000:3000
        volumes:
          - ${{ github.workspace }}/app:/app
        working-directory: /app
        run: |
          npm install
          node server.js

    container:
      image: ghcr.io/zaproxy/zaproxy:stable
      options: --user root -v ${{ github.workspace }}:/zap/wrk
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Wait for app to start
        run: |
          sleep 15
          
      - name: OWASP ZAP Baseline Scan
        run: |
          cd /zap/wrk
          zap-baseline.py -t http://app:3000 -g gen.conf -r zap_scan.md -J zap_scan.json
          
      - name: OWASP ZAP Full Scan
        if: github.event_name == 'workflow_dispatch'
        run: |
          cd /zap/wrk
          zap-full-scan.py -t http://app:3000 -g gen.conf -r zap_scan.md -J zap_scan.json
          
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_scan.md
            zap_scan.json