name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Run Docker Compose
        run: |
          docker compose up --build --abort-on-container-exit

      - name: Copy ZAP Report
        run: |
          mkdir -p zap-output
          docker cp $(docker ps -aqf "ancestor=owasp/zap2docker-stable"):/zap/wrk/zap_report.html zap-output/

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/zap_report.html
