name: ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Start App
        run: |
          cd app
          npm install
          nohup node server.js > app.log 2>&1 &

      - name: Wait for App to Start
        run: |
          echo "Waiting for app to start on http://localhost:3000"
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Create .zap directory and rules file
        run: |
          mkdir -p .zap
          cat > .zap/rules.tsv << EOF
          10016	IGNORE	(Web Browser XSS Protection Not Enabled)
          10055	IGNORE	(CSP Scanner: Wildcard Directive)
          10098	IGNORE	(Cross-Domain Misconfiguration)
          10038	IGNORE	(Content Security Policy (CSP) Header Not Set)
          90033	IGNORE	(Loosely Scoped Cookie)
          10021	WARN	THRESHOLD:4	(X-Content-Type-Options Header Missing)
          10020	WARN	THRESHOLD:3	(X-Frame-Options Header)
          10037	WARN	THRESHOLD:3	(X-Powered-By Information Leak)
          10049	WARN	THRESHOLD:5	(Storable and Cacheable Content)
          10063	WARN	THRESHOLD:5	(Permissions Policy Header Not Set)
          90004	WARN	THRESHOLD:8	(Insufficient Site Isolation Against Spectre)
          90005	WARN	THRESHOLD:10	(Sec-Fetch-Dest Header is Missing)
          EOF


      - name: Run ZAP Baseline Scan with Docker
        run: |
          # Create reports directory with proper permissions
          mkdir -p reports
          chmod 777 reports
          chmod 777 .zap
          
          # Run ZAP in Docker with proper permissions
          docker run --rm \
            --user $(id -u):$(id -g) \
            --network=host \
            -v "$(pwd)/.zap:/zap/wrk/.zap:rw" \
            -v "$(pwd)/reports:/zap/wrk/reports:rw" \
            zap2docker-weekly \
            zap-baseline.py \
            -t http://localhost:3000 \
            -c /zap/wrk/.zap/rules.tsv \
            -J reports/report_json.json \
            -w reports/report_md.md \
            -r reports/report_html.html \
            -a -I
          
          # Check result files
          ls -la reports/
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: |
            reports/report_html.html
            reports/report_md.md
            reports/report_json.json
