name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read
  issues: write


jobs:
  zap-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Start Node App
        run: |
          cd app
          npm install
          nohup node server.js > app.log 2>&1 &
          
      - name: Wait for App to Start
        run: |
          echo "Waiting for http://localhost:3000 to be ready..."
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'
          cmd_options: '-a'
          allow_issue_writing: 'false'

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            zap_scan.md
            zap_scan.html
            zap_scan.xml


