name: ZAP Baseline Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Start App
        run: |
          cd app
          npm install
          nohup node server.js > app.log 2>&1 &

      - name: Wait for App to Start
        run: |
          echo "Waiting for app to start on http://localhost:3000"
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Still waiting..."
            sleep 5
          done

      - name: Create .zap directory and rules file
        run: |
          mkdir -p .zap
          cat > .zap/rules.tsv << EOF
          10016	IGNORE	(Web Browser XSS Protection Not Enabled)
          10055	IGNORE	(CSP Scanner: Wildcard Directive)
          10098	IGNORE	(Cross-Domain Misconfiguration)
          10038	IGNORE	(Content Security Policy (CSP) Header Not Set)
          90033	IGNORE	(Loosely Scoped Cookie)
          10021	WARN	THRESHOLD:4	(X-Content-Type-Options Header Missing)
          10020	WARN	THRESHOLD:3	(X-Frame-Options Header)
          EOF

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: |
            zap_report.html
            zap_report.md
