name: Manual ZAP Scan (No Docker, No Action)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install and Start App
        run: |
          cd app
          npm install
          nohup node server.js > app.log 2>&1 &
      
      - name: Wait for App to Start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app..."
            sleep 5
          done

      - name: Install ZAP CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jre-headless wget unzip
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_Core.zip -O zap.zip
          unzip zap.zip -d zap

      - name: Run ZAP Baseline Scan
        run: |
          mkdir zap-report
          ./zap/ZAP_2.13.0/zap.sh -cmd -quickurl http://localhost:3000 -quickout zap-report/report.html -quickprogress

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_report
          path: zap-report/report.html
