name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Start Target App
        run: |
          cd app
          npm install
          node server.js &
          sleep 15
          
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
      - name: OWASP ZAP Full Scan
        if: github.event_name == 'workflow_dispatch'
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: 'http://localhost:3000'
          config_file: ".zap/policies/API-scan.policy"
          
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-reports
          path: |
            zap_scan.md
            zap_scan.json